chore: Update supports US
TypedProject/tsed pull request #1052
Opened 2020-11-05 18:05 UTC by Romakita

2020-11-06 15:14 UTC, LorianeE requested changes

2020-11-06 15:14 UTC, LorianeE commented on docs/readme.md
> + title: Support US
"Support US" ou "Support us" ? Pas la même chose 😄

2020-11-06 15:14 UTC, LorianeE commented on docs/.vuepress/components/SupportUsBlock.vue
> +                    <img :src="partner.src" :style="item.style" /> <!---->
t'as oublié une ligne de commentaire "<!---->"  (je te l'avais dit :P)

2020-11-06 15:14 UTC, LorianeE commented on docs/readme.md
> + description: Ts.ED is under MIT-license and it's an open-source project. Thank you to all our backers/sponsors/partners who contributes to promote and support our project!
Ts.ED is under MIT-license and is an open-source project. Many thanks to our backers/sponsors/partners who contribute to promote and support our project!

2020-11-06 15:16 UTC, LorianeE commented on docs/readme.md
> + description: Ts.ED is under MIT-license and it's an open-source project. Thank you to all our backers/sponsors/partners who contributes to promote and support our project!
Ou bien comme j'avais proposé avant (enfin dérivé) "Many thanks to each of our backers for contributing to promote and support our project!" 
Peut-être que 'backers/sponsors/partners' c'est un peu too much et juste "backers" ça regroupe un peu tout :)

2020-11-06 16:47 UTC, Romakita commented on docs/readme.md
> + title: Support US
Grave :)

2020-11-06 17:03 UTC, Romakita commented on docs/readme.md
> + description: Ts.ED is under MIT-license and it's an open-source project. Thank you to all our backers/sponsors/partners who contributes to promote and support our project!
Je tiens à garder le "Ts.ED is under MIT-license and is an open-source project" :)

2020-11-06 17:12 UTC, Romakita commented on docs/.vuepress/components/SupportUsBlock.vue
> +                    <img :src="partner.src" :style="item.style" /> <!---->
done 👍

2020-11-06 17:12 UTC, Romakita commented on docs/readme.md
> + title: Support US
done  :)

2020-11-07 09:52 UTC, Romakita commented
/rebase

2020-11-09 08:42 UTC, LorianeE commented on docs/readme.md
> + description: Ts.ED is under MIT-license and it's an open-source project. Thank you to all our backers/sponsors/partners who contributes to promote and support our project!
Oui oui j'ai juste pas recopié-collé mais c'était sous-entendu...

2020-11-09 08:44 UTC, Romakita commented on docs/readme.md
> + description: Ts.ED is under MIT-license and it's an open-source project. Thank you to all our backers/sponsors/partners who contributes to promote and support our project!
La modification te convient ?

2020-11-10 08:26 UTC, LorianeE requested changes

2020-11-10 08:26 UTC, LorianeE commented on docs/readme.md
>    details: A lot of decorators are provided to structure your code and define route and method.
On est sûrs pour le singulier et non pluriel de cette phrase ?

2020-11-10 08:50 UTC, Romakita commented on docs/readme.md
>    details: A lot of decorators are provided to structure your code and define route and method.
done :)

2020-11-10 09:40 UTC, LorianeE approved these changes

2020-11-11 18:02 UTC, Romakita commented on docs/.vuepress/components/SupportUsBlock.vue
> +    OpenCollectiveSponsors,
Exacte, je clean

2020-11-16 09:01 UTC, merged

2020-11-16 13:43 UTC, Romakita commented
:tada: This PR is included in version 6.9.0 :tada:

The release is available on:
- `v6.9.0`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: