feat(view): add load consolidate requires options
TypedProject/tsed pull request #1068
Opened 2020-11-11 10:22 UTC by adepanges

to handle adding requires in consolidation, i am using nunjucks for view engine and have problem when extends layout or include some view will catch by error, this changes to solve it

## Usage example

```
import { Configuration } from "@tsed/common";
import nunjucks from "nunjucks";

@Configuration({
    views: {
        root: `${rootDir}/views`,
        viewEngine: "nunjucks",
        extensions: {
            "njk": "nunjucks"
        },
        options: {
            nunjucks: {
                requires: nunjucks.configure(`${rootDir}/views`)
            }
        }
    },
})
export default class ShopApp {}

```

2020-11-11 11:30 UTC, Romakita commented
Great PR. But I doesn't seen test to cover this usecase. 
You can add it in /packages/common/src/platform/services/PlatformViews.spec.ts please :)

2020-11-11 11:41 UTC, Romakita requested changes
Missing unit test :)

2020-11-11 17:51 UTC, adepanges commented
hai @Romakita 

sorry I've never written a unit test

Should I write a new **_describe_**, or just add **_it(use case)_** for my changes?

and also how do I define a view file to test? I am looking for the **_views.ejs_** file but I can't find it
i want to make new **_view.njk_** also **_layouts/default.njk_** if it is ok

2020-11-11 18:01 UTC, Romakita commented
Hello @adepanges 

You just need to see if you configuration is correctly handled by the method.

Just add requires to initial config:

```typescript

  beforeEach(() =>
    PlatformTest.create({
      views: {
        extensions: {
          ejs: "ejs"
        },
        viewEngine: "ejs",
        options: {
          ejs: {
            global: "global",
            requires: "requires" /// add this
          }
        }
      }
    })
  );
```
Then add a it:

```typescript
 it("should load engine requires", async () => {
      const platformViews = PlatformTest.get<PlatformViews>(PlatformViews);

      expect(platformViews.consolidate.ejs.requires).to.equal('requires');
 });
```
Try it :)

2020-11-12 11:31 UTC, Romakita commented
@adepanges There are some issue on unit test, can you fix it please ?

2020-11-12 11:33 UTC, adepanges commented
yes checking it, try to run unit test in my local also

2020-11-12 11:34 UTC, Romakita commented
yes just run `yarn test` :)

2020-11-13 06:50 UTC, Romakita requested changes

2020-11-13 06:50 UTC, Romakita commented on packages/common/src/platform/services/PlatformViews.spec.ts
>          }
add just before the first afterEach this code to fix your unit test:

```typescript
  afterEach(() => {
    const platformViews = PlatformTest.get<PlatformViews>(PlatformViews);

    delete platformViews.consolidate.requires.ejs;
  });
```

Because we add fake requires, we need to clean the  `platformViews.consolidate.requires.ejs` after the unit test, to be sure the integration test works ^^.

2020-11-13 06:51 UTC, adepanges commented on packages/common/src/platform/services/PlatformViews.spec.ts
>          }
okey thanks let meed add it, and run test

2020-11-13 07:24 UTC, Romakita approved these changes

2020-11-13 07:25 UTC, merged

2020-11-13 07:34 UTC, Romakita commented
:tada: This PR is included in version 6.7.0 :tada:

The release is available on:
- `v6.7.0`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: