fix(schema): Added file upload support
TypedProject/tsed pull request #1082
Opened 2020-11-12 04:03 UTC by dvarnai

## Informations

Type | Breaking change
---|---
Fix | No

****

## Description

This commit tries to reintroduce file support. I'm not sure if this is the best way to do this, so please let me know if you'd like anything changed.

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2020-11-12 05:42 UTC, dvarnai commented
Currently, this seems to create the OpenApi specification properly, however, validation fails as AJV doesn't know format: binary, also it tries to validate PlatformMulterFile as a string and fails

2020-11-12 07:19 UTC, Romakita requested changes

2020-11-12 07:19 UTC, Romakita commented on packages/schema/src/domain/JsonOperation.ts
> +              const schema = parameter.$schema.get("type") === "array" ? parameter.$schema.itemSchema() : parameter.$schema;
I think this code should be in JsonParameter class instead of Operation (in `JsonParameter.toJSON`).
Finally we just need to instrument correctly where the parameters will be pushed:
```typescript
if ([JsonParameterTypes.BODY, JsonParameterTypes.FILES].includes(parameter.get("in"))) {
    bodyParameters.push(parameter);
}
```

2020-11-12 07:36 UTC, Romakita commented
Hello @dvarnai 

I suggest to create a unit test to cover you scenario:
> packages/schema/src/decorators/operations/in.spec.ts

```typescript
describe("@In", () => {
  it("JsonParameterTypes.FILES with OS2", () => {
     class MyController {
      @OperationPath("POST", "/")
      method(@In(JsonParameterTypes.FILES) @Name("file") file: string) {
      } 
    }

    const result = getSpec(Controller, {
      specType: SpecTypes.SWAGGER
    });

    expect(result).to.deep.equal({...});
  });

  it("JsonParameterTypes.FILES with OS3", () => {
     class MyController {
      @OperationPath("POST", "/")
      method(@In(JsonParameterTypes.FILES) @Name("file") file: string) {
      } 
    }

    const result = getSpec(Controller, {
      specType: SpecTypes.OPENAPI
    });

    expect(result).to.deep.equal({...});
  });
});
```

2020-11-12 08:00 UTC, Romakita commented
> Currently, this seems to create the OpenApi specification properly, however, validation fails as AJV doesn't know format: binary, also it tries to validate PlatformMulterFile as a string and fails. 

In your PR on don't see how the given schema to AJV can have a binary format. But I think if you move the code to JsonParameter, the problem will be solved.

In JsonParameter:
```typescript
   if (this.get("in") === JsonParameterTypes.FILES) {
      const isOpenApi = options.specType === SpecTypes.OPENAPI;

      const schema = {
        type: isOpenApi ? "string" : "file",
        format: isOpenApi ? "binary" : undefined
      };

      if (jsonSchema.type === "array") {
        jsonSchema.items = cleanObject({
          ...jsonSchema.items,
          ...schema
        });

        parameter.schema = jsonSchema;
      } else {
        parameter.schema = cleanObject({
          ...jsonSchema,
          ...schema
        });
      }
    }
```

> Furthermore, ".0" gets appended to the name of the field in swagger.json. Sorry I couldn't be more useful

Hum... I haven't solution yet. I propose to fix that later :). Wait and see the requested change and after we will find a solution.

2020-11-12 08:01 UTC, Romakita commented on packages/schema/src/domain/JsonOperation.ts
> +              const schema = parameter.$schema.get("type") === "array" ? parameter.$schema.itemSchema() : parameter.$schema;
In JsonParameter, line just after `parameter.required = parameter.required || this.get("in") === "path";` line-60:

```typescript
if (this.get("in") === JsonParameterTypes.FILES) {
      const isOpenApi = options.specType === SpecTypes.OPENAPI;

      const schema = {
        type: isOpenApi ? "string" : "file",
        format: isOpenApi ? "binary" : undefined
      };

      if (jsonSchema.type === "array") {
        jsonSchema.items = cleanObject({
          ...jsonSchema.items,
          ...schema
        });

        parameter.schema = jsonSchema;
      } else {
        parameter.schema = cleanObject({
          ...jsonSchema,
          ...schema
        });
      }
    }
```

2020-11-12 08:02 UTC, Romakita commented on packages/schema/src/domain/JsonOperation.ts
> +              const schema = parameter.$schema.get("type") === "array" ? parameter.$schema.itemSchema() : parameter.$schema;
I think by this way, the jsonSchema generated for AJV won't fail, because, format will be generated only for OS2 and OS3 :)

2020-11-12 11:37 UTC, dvarnai commented
Thanks for the review. I just pushed another commit. It seems we can't do this purely in JsonParameter.ts as the $schema is added directly as a property to JsonOperation, so now I'm manually calling JsonParameter.toJSON() in JsonOperation when building the schema.

2020-11-12 11:54 UTC, Romakita commented
To solve issue with the expression we need to update the unit test in the first time:

> See: packages/common/src/platform/decorators/multer/multipartFile.spec.ts

```diff
      expect(getSpec(TestController)).to.deep.eq({
        paths: {
          "/": {
            post: {
              consumes: ["multipart/form-data"],
              operationId: "testControllerTest",
              parameters: [
+                {
+                  in: "body",
+                  name: "body",
+                  required: false,
+                  schema: {
+                    properties: {
+                      "file1": {   // name without index
+                        $ref: "file"
+                      }
+                    },
+                    type: "object"
+                  }
+                }
              ],
              responses: {
                "400": {
                  description:
                    "<File too long | Too many parts | Too many files | Field name too long | Field value too long | Too many fields | Unexpected field>  [fieldName] Example: File too long file1",
                  schema: {
                    type: "string"
                  }
                }
              },
              tags: ["TestController"]
            }
          }
        },
        tags: [
          {
            name: "TestController"
          }
        ]
      });
    });
```

Then we need to fix JsonOperation to build the correct spec. To solve it, we can add `JsonParameter.getName` method, which will return the correct name.

```typescript
class JsonParameter {
  getName() {
    const name = this.get("name");

    if (this.get("in") === JsonParameterTypes.FILES) {
      return name.split(".")[0];
    }

    return name;
  }
}
```
And finally we can use this new method in JsonOperation file (fn: buildSchemaFromBodyParameters):

```diff
  parameters.forEach((parameter) => {
-    const name = parameter.get('name')
+    const name = parameter.getName()
```

What do you think :)?

2020-11-12 23:32 UTC, dvarnai commented
PR ready :)

2020-11-13 06:37 UTC, Romakita requested changes

2020-11-13 06:37 UTC, Romakita commented on packages/common/src/platform/decorators/multer/multipartFile.spec.ts
> +    expect(store.get(PlatformMulterMiddleware)).to.deep.eq({
expect must be alway in a it :) not directly in a describe.

```typescript
it("should store metadata", () => {
     const store = Store.fromMethod(TestController, "test");
     expect(store.get(PlatformMulterMiddleware)).to.deep.eq({
      fields: [
        {
          maxCount: 1,
          name: "file1"
        }
      ]
    });
});

it("should create param with the right configuration", () => {
    const param = ParamMetadata.get(TestController, "test", 0);
    expect(param.expression).to.eq("file1.0");
    expect(param.paramType).to.eq(ParamTypes.FILES);
});

```

2020-11-13 06:37 UTC, Romakita commented on packages/common/src/platform/decorators/multer/multipartFile.spec.ts
> +    const store = Store.fromMethod(TestController, "test");
same thing :)

2020-11-13 06:38 UTC, Romakita commented
Thanks @dvarnai :)
Just to small change and it'll be ok :)

2020-11-13 07:38 UTC, dvarnai commented on packages/common/src/platform/decorators/multer/multipartFile.spec.ts
> +    const store = Store.fromMethod(TestController, "test");
ah you're right, sorry about that

2020-11-13 08:09 UTC, Romakita commented on packages/common/src/platform/decorators/multer/multipartFile.spec.ts
> +    const store = Store.fromMethod(TestController, "test");
No worries ;)

2020-11-13 08:09 UTC, Romakita approved these changes

2020-11-13 08:10 UTC, merged

2020-11-13 08:20 UTC, Romakita commented
:tada: This PR is included in version 6.7.1 :tada:

The release is available on:
- `v6.7.1`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.7.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: