fix(typeorm): Support TypeORM ConnectionOptions without name property
TypedProject/tsed pull request #1334
Opened 2021-04-06 12:22 UTC by yuki-takei

## Information

Type | Breaking change
---|---
Fix | No

****

## Description
- refs #1332 

## Todos

- [x] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

2021-04-06 18:10 UTC, Romakita requested changes

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/TypeORMModule.ts
> +    this.settings = configuration.get<ConnectionOptions[]>("typeorm") || [];
```typescript
this.settings = configuration.get<ConnectionOptions[]>("typeorm", [])
```

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/TypeORMModule.ts
> +    this.settings = configuration.get<ConnectionOptions[]>("typeorm") || [];
To avoid coverage issue :)

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/services/TypeORMService.ts
> +    const name = connectionOptions.name;
const name = getValue(connectionOptions, 'name', 'default')

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/services/TypeORMService.ts
> +    const name = connectionOptions.name;
To avoid coverage issue and to have always a name with `default`

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/services/TypeORMService.ts
> +    this.injector.logger.info(`Create connection with typeorm to database: ${name ?? "default"}`);
So we can just set the fowolling code `${name}`

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/services/TypeORMService.ts
> +      this.injector.logger.info(`Connected with typeorm to database: ${connection.name}`);
`${name}`

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/utils/createConnection.ts
> +  const name = connectionOptions.name ?? "default";
const name = getValue(connectionOptions, 'name', 'default')

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/utils/createConnection.ts
> +  if (!connectionManager.has(name)) {
perfect :)

2021-04-06 18:10 UTC, Romakita commented on packages/typeorm/src/utils/createConnection.ts
> +    await connection.connect();
perfect

2021-04-06 18:11 UTC, Romakita commented
Hello @yuki-takei 
Thanks a lot for the simplification about the connections management!
I added some small change to avoid coverage issue ;)

2021-04-07 19:41 UTC, yuki-takei commented on packages/typeorm/src/services/TypeORMService.ts
> +  has(id: string): boolean {
Removed default value for coverage.

Because only TypeORMService self uses this `has` method and the arg `id` will be initialized as non-null value;

2021-04-07 19:41 UTC, yuki-takei commented on packages/typeorm/src/utils/createConnection.ts
> -  connection.$onDestroy = connection.$onDestroy || (() => connection.isConnected && connection.close());
Removed `$onDestroy` because `TypeORM.Connection` instance is not an implement of `onDestroy`.

`TypeORMService.closeConnections` invokes `Connection.close()` for all connections.

2021-04-07 19:47 UTC, yuki-takei commented
@Romakita All checks have passed. Please check it again.

2021-04-08 06:12 UTC, Romakita commented on packages/typeorm/src/utils/createConnection.ts
> -  connection.$onDestroy = connection.$onDestroy || (() => connection.isConnected && connection.close());
Oh great :)

2021-04-08 06:15 UTC, Romakita requested changes

2021-04-08 06:15 UTC, Romakita commented on packages/typeorm/src/services/TypeORMService.ts
> +  has(id: string): boolean {
But this change is breaking change. 
If somebody use the method .has() without parameter in his code, this new version will throw a compilation error :)

2021-04-08 07:35 UTC, yuki-takei commented on packages/typeorm/src/services/TypeORMService.ts
> +  has(id: string): boolean {
Hmm, I suppose so.
OK, I'll revert it and add some test codes.

2021-04-08 18:57 UTC, Romakita approved these changes

2021-04-08 18:59 UTC, merged

2021-04-08 18:59 UTC, Romakita commented
Thanks @yuki-takei for the PR :D

2021-04-08 19:14 UTC, Romakita commented
:tada: This PR is included in version 6.38.5 :tada:

The release is available on:
- `v6.38.5`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.38.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: