feat(before-deserialize-decorator): Add BeforeDeserialize decorator
TypedProject/tsed pull request #1337
Opened 2021-04-07 16:43 UTC by xCryzed

## Information

Type | Breaking change
---|---
Feature | No

****

## Description
Closes #1336.

2021-04-07 17:38 UTC, Romakita requested changes

2021-04-07 17:38 UTC, Romakita commented on packages/json-mapper/src/utils/deserialize.ts
> +  const out: any = new type(alterBeforeDeserialize(src, store.schema, options));
Hum ok, maybe to avoid confusing behavior (and answer your question about the `return data`), the following code will more appropriate and throw an error if data isn't correctly returned:
```diff
-   const out: any = new type(alterBeforeDeserialize(src, store.schema, options));
+  src = alterBeforeDeserialize(src, store.schema, options);
+  const out: any = new type(src);
```
In this case if data isn't returned, the mapping will fail!

2021-04-07 18:30 UTC, xCryzed commented on packages/json-mapper/src/utils/deserialize.ts
> +  const out: any = new type(alterBeforeDeserialize(src, store.schema, options));
done :)

2021-04-08 06:33 UTC, Romakita approved these changes

2021-04-08 06:33 UTC, Romakita commented
Great Job @xCryzed ;)

2021-04-09 10:34 UTC, Romakita approved these changes

2021-04-09 10:34 UTC, merged

2021-04-09 10:50 UTC, Romakita commented
:tada: This PR is included in version 6.39.0 :tada:

The release is available on:
- `v6.39.0`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.39.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: