Objection.js plugin (WIP)
TypedProject/tsed pull request #928
Opened 2020-09-20 11:35 UTC by stefanvanherwijnen

I started working on a @tsed/objection plugin to integrate [Objection.js](https://vincit.github.io/objection.js/) into Ts.ED.
Currently it's just very basic functionality based on the gist (https://gist.github.com/Romakita/32da7db47264f29bb535c6546459de9d)

A few questions:
- What functionality do I need to add to integrate it into Ts.ED the correct way (think services, providers etc)?
- Knex depends on database connection packages (pg, sqlite, mysql etc) which are not installed by default. Because the database connection is created inside the plugin, installing them into the main project does not work. How should I provide support for all databases without actually installing all the required packages?
- Currently the `Model` class is re-exported inside the plugin to make sure the same `Model` is used in the project and the plugin. This seems to work but I am wondering if this is the best way?

I had a look at the TypeORM package but that one seems much more complicated as it offers multiple connections etc, which is not possible with knex by default. I'll finish the plugin, but some pointers and feedback would be appreciated.

----------------------------------------------------------------------
To create a connection:
```ts
import {Configuration, registerProvider} from "@tsed/di";
import {setupObjectionJs} from "@tsed/objection";
import Knex, {Config} from "knex";

export const CONNECTION = Symbol.for("DEFAULT_CONNECTION");
export type CONNECTION = ReturnType<Knex>;

registerProvider({
  provide: CONNECTION,
  deps: [Configuration],
  useFactory(configuration: Configuration) {
    const settings = configuration.get<Config[]>("knex")!;
    const connectionOptions = settings[0];

    return setupObjectionJs(connectionOptions!);
  },
});
```
`models/User.ts`:
```ts
import {Required, MinLength, MaxLength} from "@tsed/common";
import {Model, Entity} from "@tsed/objection";

@Entity("users")
export class User extends Model {
  @Required()
  @MinLength(1)
  @MaxLength(25)
  name: string;
}
```

2020-09-20 16:56 UTC, Romakita approved these changes

2020-09-20 16:56 UTC, Romakita commented on packages/objection/package.json
> +    "knex": "^0.21.5",
In fact, you don't need to keep theses dependencies here (knex, objection, pg, sqlite3)
This is my error when a created typeorm package. Because typeorm release often a new package, isn't easy to maintain the package.json up-to-date. So I moved in v6, typeorm to devDependencies (and peerDependencies also) section and in the readme, I added the instruction to install correctly the tsed package. 
It'll solve/prevent many issues :) but we need to correctly description the installation guide ;)

example:

To install @tsed/objection you have to install the following packages:
```typescript
npm i --save objection knex @types/objections @types/knex @tsed/objection
npm i --save pg  // change by the expected database
```

2020-09-20 16:56 UTC, Romakita commented on packages/objection/src/decorators/Entity.ts
> +        return tableName || (nameOf(target) + 's')
For: (nameOf(target) + 's') 
I propose to use a [pluralize](https://www.npmjs.com/package/pluralize) npm module (as dependencies) to prevent automatic naming error ^^. What do you think?

2020-09-20 16:56 UTC, Romakita commented on packages/objection/src/index.ts
> +      knex: Config[];
Ok if Objection support only one database, we don't need to provide an array interface, it could be confusing for your users ;)

2020-09-20 16:56 UTC, Romakita commented on packages/objection/src/utils/connect.ts
> +    $log.error('Knex connection failed')
I think, catch the error connection isn't wanted by. Developpers prefer to crash the server when the connection fail ;). 

So the code can be simplied:
```typescript
function createConnection(connectionOptions: Config){
  const connection = Knex((connectionOptions)
  Model.knex(connection)
  return connection
}
```

2020-09-20 16:56 UTC, Romakita commented on packages/objection/src/utils/connect.ts
> +export class Model extends ObjectionJSModel {}
Ok. This is third point :)
If you declare objection as devDependencies and peerDependencies, re-export Model from Objection won't make sense, because I'll manipulate always the same Model class :) (problem solved by the peerDependencies ^^ )

2020-09-20 17:02 UTC, Romakita commented
Hello @stefanvanherwijnen 
This is a good first PR, I'm very impatient to see the next commits 👍 
I answered to your differents questions by reviewing your PR and adding notes.
I approvedchange the PR  instead of request by error (wrong click XD). But it's not really important at this step.

So the your different questions will be solved by moving the dependencies to devDependencies and peerDependencies. Keep the caret "^" before the module version. Developpers will be free to install version of Objection,Knex, etc... for you, it'll be easier to maintain the @tsed/objections package. 

Again good job ;)
Romain

2020-09-21 17:42 UTC, stefanvanherwijnen commented on packages/objection/src/decorators/Entity.ts
> +        return tableName || (nameOf(target) + 's')
If you ask me I would just use `return tableName`. I copied the pluralization from your gist, but my personal opinion is to let the user define the table name and be responsible for the pluralization. `pluralize` will probably handle most edge cases, but I don't like having to load an entire module just to pluralize `person` to `people`.
But that's just my opinion.

2020-09-21 17:48 UTC, stefanvanherwijnen commented
Thanks for the feedback. I noticed the peerDependencies field and only after submitting the thought struck me that I should probably have used that.
I'll fix the things you mentioned later this week, and I'll also write some tests to check if everything works as it should.

Let me know if there is anything specific I need to take into account, otherwise I'll just keep it as simple as possible (e.g. support only one connection).

2020-09-24 04:32 UTC, Romakita commented on packages/objection/src/decorators/Entity.ts
> +        return tableName || (nameOf(target) + 's')
You’ve right stay simple :)

2020-09-26 14:11 UTC, stefanvanherwijnen commented
Could you help me out on how to retrieve the provided Ajv instance from `@tsed/ajv`?
I want to add
```
Object.defineProperty(target, "createValidator", {
  get() {
    return ajv;
  }
});
```
to Entity.ts, with `ajv` as an argument. However, I can't seem to figure out how to retrieve the ajv instance which is created by `registerProvider` in `@tsed/ajv`.

This is to support custom validators in the json schema.

2020-09-27 15:29 UTC, Romakita commented
Hello @stefanvanherwijnen 
The problem is the Ajv Instance built by Ts.ED is only available when you start the server with the container. Here, the createValidator method is static and live outside the DI container. You are only able to give your own Ajv instance.

See you :)

2020-09-29 13:41 UTC, stefanvanherwijnen commented
Makes sense. I'll first do some testing with custom validators and then try to see if I can incorporate them into an ajv instance globally. Just trying to prevent having multiple (equal) validators across the application.

2020-10-29 08:29 UTC, Romakita requested changes

2020-10-29 08:29 UTC, Romakita commented on docs/tutorials/objection.md
> +# Objecion.js
Objection :)

2020-10-29 08:29 UTC, Romakita commented on docs/tutorials/objection.md
> +You can use the `Entity` decorator to create your models and make them work with Objection.js. `Entity` expects the table name as its argument.
You can replace `Entity` by @@Entity@@ to link automatically the Entity to his Api reference page :)

Example:
<img width="120" alt="Capture d’écran 2020-10-29 à 09 24 56" src="https://user-images.githubusercontent.com/1763311/97543509-a1954500-19c8-11eb-84f7-0d4befc1408f.png">

2020-10-29 08:29 UTC, Romakita commented on docs/tutorials/objection.md
> +```
Can you add theses lines please:


```
## Author 

<GithubContributors :users="['stefanvanherwijnen']"/>

## Maintainers

<GithubContributors :users="['stefanvanherwijnen']"/>

<div class="container--centered container--padded">
<a href="/contributing.html" class="nav-link button">
 Become maintainer
</a>
</div>
```
 
This code will display you github account ;)

2020-10-29 08:29 UTC, Romakita commented on docs/tutorials/objection.md
> +Add a `knex` configuration to your TSed configuration (see: http://knexjs.org/#Installation-client for options).
Ts.ED

2020-10-29 08:29 UTC, Romakita commented on packages/objection/src/decorators/IdColumn.ts
> +// export function IdColumn (target: Object, propertyKey: string): PropertyDecorator {
We can remove this file?

2020-10-29 08:30 UTC, Romakita commented
Hello @stefanvanherwijnen 
Do you need help to finish this plugin ?
I also added some request changes :) 

Another point, do you need this feature on v5 branch? 
See you
Romain

2020-10-29 11:04 UTC, stefanvanherwijnen commented
My plan was to finish it by using it in a project and see what's still missing, but I haven't had the time unfortunately.
I'll fix the things you mentioned, and finish the rest, but I can't tell you when it will be done.

You can skip this for v5. I just want to make sure it works properly before I finish the PR.

2020-11-11 10:05 UTC, Romakita commented
/rebase

2020-11-11 10:07 UTC, Romakita commented
I suggest to merge this PR and add a text on the readme and documentation to tell that this module is under work in progress / alpha. It allow you to test the module :)

2020-11-11 10:15 UTC, stefanvanherwijnen commented
Yes, good point. I was trying to integrate it into the CLI but without an upstream package you quickly get stuck. The PR can be merged, but as you said it is still in alpha. I'll make a new PR for any additions.

2020-11-11 11:17 UTC, Romakita commented
Yes no worries about that, I'll configure the package under alpha :) and add the badge on documentation. 
I'll trigger you when the package is available ;)

2020-11-11 12:46 UTC, Romakita approved these changes

2020-11-15 15:02 UTC, merged