feat(aws): Add new package @tsed/platform-aws
TypedProject/tsed pull request #960
Opened 2020-10-05 09:00 UTC by Romakita

## Informations

Type | Breaking change
---|---
Feature | No

****

## Description
A package to configure Ts.ED with AWS

## Usage example

## Usage

Create a new `LambdaServer.ts` in `src` directory:

```typescript
import {PlatformAws} from "@tsed/platform-aws";
import "@tsed/platform-express" 
// or import "@tsed/platform-koa"

PlatformAws.bootstrap(Server, {
 aws: {
   binaryMimeTypes: [ // optional
     // mime types list 
   ]
 },
 // additional Ts.ED options. See https://tsed.io/tutorials/aws.html
});

// Handler used by AWS
export const handler = PlatformAws.callback();
```

Then create `lambda.js` on your root project:

```javascript
module.exports = require("./dist/LambdaServer.js");
```

This file will be used by AWS to forward request to your application.

Finally, [package and create your Lambda function](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html), 
then configure a simple proxy API using Amazon API Gateway and integrate it with your Lambda function.

See more details on [`aws-serveless-express`](https://github.com/awslabs/aws-serverless-express) project.

## Getting the API Gateway event object

This package includes decorators to easily get the event object Lambda receives from API Gateway:

```typescript
import {Controller, Get} from "@tsed/common"; 
import {AwsEvent, AwsContext} from "@tsed/platform-aws"; 

@Controller('/')
class MyCtrl {
 @Get('/')
 get(@AwsEvent() event: any, @AwsContext() context: any) {
   console.log("Event", apiGateway.event);
   console.log("Context", apiGateway.context);
   
   return apiGateway;
 }
}
```

## Todos

- [x] Tests
- [ ] Coverage
- [x] Example
- [x] Documentation

2020-10-05 15:04 UTC, LorianeE requested changes

2020-10-05 15:04 UTC, LorianeE commented on packages/platform-aws/test/app/Server.ts
> +   * This method let you configure the middleware required by your application to works.
This method let**s** you configure the middleware required by your application to **work**.

2020-10-06 05:59 UTC, Romakita commented on packages/platform-aws/test/app/Server.ts
> +   * This method let you configure the middleware required by your application to works.
done

2020-10-06 05:59 UTC, Romakita commented on packages/platform-aws/readme.md
> +This package includes decorators to easily get the event object Lambda receives from API Gateway:
Done

2020-10-06 07:27 UTC, LorianeE commented on packages/platform-aws/test/app/Server.ts
> +   * This method let you configure the middleware required by your application to works.
Bah tu l'as carrément enlevé ?

2020-10-06 07:46 UTC, merged

2020-10-06 07:55 UTC, Romakita commented
:tada: This PR is included in version 6.0.0-beta.9 :tada:

The release is available on:
- `v6.0.0-beta.9`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.0.0-beta.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-10-12 10:05 UTC, Romakita commented
:tada: This PR is included in version 6.0.0-rc.1 :tada:

The release is available on:
- `v6.0.0-rc.1`
- [GitHub release](https://github.com/TypedProject/tsed/releases/tag/v6.0.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: